export const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

export const siteConfig = {
	name: "KeyShop",
	description: "Generated by create next app",
	url: BASE_URL,
	ogImage: `${BASE_URL}/og.jpg`,
	links: {
		github: "https://github.com/whoyoux/key-shop",
	},
};
